# Bronze - Countries Data

## Setup Environment and Prepare data

In [ ]:
from letterboxd_data_pipeline.load_data import load_files_from_layer
from letterboxd_data_pipeline.explore_data import is_possible_na

bronze_df = load_files_from_layer(layer="bronze", file_list=["countries.parquet"])
bronze_countries_df = bronze_df["countries"]

Start loading data...
Loading: data/bronze/countries
Done!
Finish loading.

## Simple Explore

In [2]:
bronze_countries_df.describe(include="all")

             id country
count    693476  693476
unique   617192     247
top     1188661     USA
freq         30  174489

In [3]:
bronze_countries_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 693476 entries, 0 to 693475
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   id       693476 non-null  object
 1   country  693476 non-null  object
dtypes: object(2)
memory usage: 10.6+ MB

In [4]:
bronze_countries_df.head(10)

        id      country
0  1000001           UK
1  1000001          USA
2  1000002  South Korea
3  1000003          USA
4  1000004      Germany
5  1000004          USA
6  1000005    Hong Kong
7  1000005          USA
8  1000006           UK
9  1000006          USA

## Number of NA

In [5]:
bronze_countries_df.isna().sum()

id         0
country    0
dtype: int64

## Possible NA

In [6]:
possible_na_df = bronze_countries_df[is_possible_na(bronze_countries_df["country"])]
possible_na_df

Empty DataFrame
Columns: [id, country]
Index: []

## Movie with most countries

In [7]:
bronze_countries_df.groupby("id").agg(total_countries=("country", "count")).sort_values(by="total_countries",ascending=False)

         total_countries
id
1188661               30
1106357               26
1116437               26
1181951               25
1038152               25
...                  ...
1260690                1
1260691                1
1260692                1
1260693                1
1260682                1

[617192 rows x 1 columns]