# Bronze - Movies Data

## Setup Environment and Prepare data

In [1]:
from letterboxd_data_pipeline.load_data import load_files_from_layer
from letterboxd_data_pipeline.explore_data import is_possible_na

# bronze_df = load_files_from_layer(layer="bronze", file_list=["movies"])
bronze_movies_df =load_files_from_layer(layer="bronze", file_list=["movies.parquet"])["movies"]

Start loading data...
Loading: data/bronze/movies.parquet
Done!
Finish loading.

## Simple Explore

In [2]:
bronze_movies_df.describe(include="all")

,id,name,date,tagline,description,minute,rating
count,941597,941587,849684,139387,780785,760027,90999
unique,941597,795421,149,135521,763348,1034,355
top,1000001,Home,2023,animation short,Mexican feature film,90,3.44
freq,1,143,43414,100,893,29442,1118

In [3]:
bronze_movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 941597 entries, 0 to 941596
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   id           941597 non-null  object
 1   name         941587 non-null  object
 2   date         849684 non-null  object
 3   tagline      139387 non-null  object
 4   description  780785 non-null  object
 5   minute       760027 non-null  object
 6   rating       90999 non-null   object
dtypes: object(7)
memory usage: 50.3+ MB

In [4]:
bronze_movies_df.head(10)

,id,name,date,tagline,description,minute,rating
0,1000001,Barbie,2023,She's everything. He's just Ken.,Barbie and Ken are having the time of their li...,114,3.86
1,1000002,Parasite,2019,Act like you own the place.,"All unemployed, Ki-taek's family takes peculia...",133,4.56
2,1000003,Everything Everywhere All at Once,2022,The universe is so much bigger than you realize.,An aging Chinese immigrant is swept up in an i...,140,4.3
3,1000004,Fight Club,1999,Mischief. Mayhem. Soap.,A ticking-time-bomb insomniac and a slippery s...,139,4.27
4,1000005,La La Land,2016,Here's to the fools who dream.,"Mia, an aspiring actress, serves lattes to mov...",129,4.09
5,1000006,Oppenheimer,2023,The world forever changes.,The story of J. Robert Oppenheimer's role in t...,181,4.23
6,1000007,Interstellar,2014,Mankind was born on Earth. It was never meant ...,The adventures of a group of explorers who mak...,169,4.35
7,1000008,Joker,2019,Put on a happy face.,"During the 1980s, a failed stand-up comedian i...",122,3.85
8,1000009,Dune,2021,"Beyond fear, destiny awaits.","Paul Atreides, a brilliant and gifted young ma...",155,3.9
9,1000010,Pulp Fiction,1994,Just because you are a character doesn't mean ...,"A burger-loving hit man, his philosophical par...",154,4.26

## Number of NA

In [5]:
bronze_movies_df.isna().sum()

id                  0
name               10
date            91913
tagline        802210
description    160812
minute         181570
rating         850598
dtype: int64

## Possible NA

In [6]:
possible_na_df = bronze_movies_df[
  is_possible_na(bronze_movies_df["name"]) | 
  is_possible_na(bronze_movies_df["tagline"]) |
  is_possible_na(bronze_movies_df["description"])
]
possible_na_df

,id,name,date,tagline,description,minute,rating
329933,1329934,Nan,2020,None,"A portrait that follows Nan, my uncle and the ...",80,None
341998,1341999,No Return,2021,none,A video store crew close up for the evening an...,6,None
357299,1357300,Trung Tâm Asia Niềm Vui Giáng Sinh 2012,None,none,Joy of Christmas,130,None
770934,1770935,none,None,None,Plot unknown.,None,None

## Most Popular Movie Name

In [7]:
# Always use this line to sample the entire data to verify the code swiftly
popular_name_df = bronze_movies_df.copy(True)

popular_name_df.groupby("name").agg(total_count=("id","count")).sort_values(by="total_count", ascending=False)

                               total_count
name
Home                                   143
Untitled                               118
Alone                                  108
Mother                                  98
Love                                    76
...                                    ...
History of Manawan - Part Two            1
History of Manawan – Part Two            1
History of Memory                        1
History of Micronesia                    1
History of Hell                          1

[795421 rows x 1 columns]