# Bronze - Language Data

## Setup Environment and Prepare data

In [1]:
from letterboxd_data_pipeline.load_data import load_files_from_layer
from letterboxd_data_pipeline.explore_data import is_possible_na

# bronze_df = load_files_from_layer(layer="bronze", file_list=["languages"])
bronze_language_df = load_files_from_layer(layer="bronze", file_list=["languages.parquet"])["languages"]

Start loading data...
Loading: data/bronze/languages.parquet
Done!
Finish loading.

## Simple Explore

In [2]:
bronze_language_df.describe(include="all")

             id      type language
count   1038762   1038762  1038762
unique   905578         3      192
top     1285566  Language  English
freq         21    848466   473068

In [3]:
bronze_language_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1038762 entries, 0 to 1038761
Data columns (total 3 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   id        1038762 non-null  object
 1   type      1038762 non-null  object
 2   language  1038762 non-null  object
dtypes: object(3)
memory usage: 23.8+ MB

In [4]:
bronze_language_df.head(10)

        id              type   language
0  1000001          Language    English
1  1000002  Primary language     Korean
2  1000002   Spoken language    English
3  1000002   Spoken language     German
4  1000002   Spoken language     Korean
5  1000003  Primary language    English
6  1000003   Spoken language  Cantonese
7  1000003   Spoken language    Chinese
8  1000003   Spoken language    English
9  1000004          Language    English

## Number of NA

In [5]:
bronze_language_df.isna().sum()

id          0
type        0
language    0
dtype: int64

In [6]:
possible_na_df = bronze_language_df[is_possible_na(bronze_language_df["type"]) | is_possible_na(bronze_language_df["language"])]
possible_na_df

Empty DataFrame
Columns: [id, type, language]
Index: []

### Movie with Most Language of all Type

In [7]:
movie_with_most_lang_df = bronze_language_df.copy(True)

grouped_source_df = movie_with_most_lang_df.groupby(by=["id", "type"])

movie_with_most_lang_df["language_count"] = grouped_source_df["language"].transform(len)

movie_with_most_lang_df = movie_with_most_lang_df[
    ["id", "type", "language", "language_count"]
].sort_values(["language_count"], ascending=[False])

movie_with_most_lang_df

             id             type    language  language_count
350085  1285566  Spoken language        Thai              20
350084  1285566  Spoken language  Vietnamese              20
350083  1285566  Spoken language      Arabic              20
350082  1285566  Spoken language     Spanish              20
350081  1285566  Spoken language     Chinese              20
...         ...              ...         ...             ...
394650  1326367         Language     Spanish               1
394651  1326368         Language     English               1
394652  1326369         Language     Russian               1
394653  1326370         Language     English               1
394637  1326356         Language     English               1

[1038762 rows x 4 columns]