# Brone - Actors - Possible NAs

In [2]:
from letterboxd_data_pipeline.load_data import load_files_from_layer
from letterboxd_data_pipeline.explore_data.explore_data import is_possible_na
import numpy as np

bronze_df = load_files_from_layer(layer="bronze", file_list=["actors.parquet"])["actors"]
bronze_df.info()

Start loading data...
Loading: data/bronze/actors.parquet
Done!
Finish loading.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5798450 entries, 0 to 5798449
Data columns (total 3 columns):
 #   Column  Dtype
---  ------  -----
 0   id      object
 1   name    object
 2   role    object
dtypes: object(3)
memory usage: 132.7+ MB

In [8]:
nas_df = bronze_df[bronze_df["name"].isna() | bronze_df["role"].isna()]
nas_df

              id               name  role
3263     1000047         Ronan Hice  None
3267     1000047           Jon Eyez  None
3276     1000047         Kerry Sims  None
3280     1000047  Keniaryn Mitchell  None
3283     1000047       Ashley Toman  None
...          ...                ...   ...
5798439  1941563           Lan Xiya  None
5798440  1941563               黄子弘凡  None
5798444  1941596     Sandrine Pinna  None
5798448  1941597     Hiroshi Mikami  None
5798449  1941597      Keiko Oginome  None

[1361561 rows x 3 columns]

In [7]:
possible_nas_df = bronze_df[is_possible_na(bronze_df["name"]) | is_possible_na(bronze_df["role"])]
possible_nas_df

              id                 name               role
18917    1000301            Judy Kuhn                Nan
80182    1001571    Cordelia Richards                Nan
109214   1002291         Mavis Paenga                Nan
128884   1002801        Connie Danese                Nan
159169   1003601        Eileen Colgan                Nan
...          ...                  ...                ...
5461595  1783487       Zillah Bateman                Nan
5652329  1860568                   Na               None
5656233  1862670      Christine Uhebe                Nan
5787871  1935653  Marie-Philomène Nga                 Na
5792614  1938925                   Na  A Letterboxd User

[174 rows x 3 columns]

In [10]:
role_nas_df = bronze_df[is_possible_na(bronze_df["role"])]
role_nas_df.groupby("role").agg(total=("id","count"))

      total
role
Na       18
Nan     154

In [11]:
name_nas_df = bronze_df[is_possible_na(bronze_df["name"])]
name_nas_df.groupby("name").agg(total=("id","count"))

      total
name
Na        2

Conclusion for this exploration is that both name and role can not confidently treated as `None`.