# Bronze - Actors - Column Characters Frequency Explore

In [1]:
import pandas as pd
import plotly.express as px
from letterboxd_data_pipeline.load_data import load_files_from_layer
from letterboxd_data_pipeline.explore_data.char_frequency import gen_char_frequency_df

bronze_df = load_files_from_layer(layer="bronze", file_list=["actors.parquet"])
target_df = bronze_df["actors"]

Start loading data...
Loading: data/bronze/actors.parquet
Done!
Finish loading.

In [2]:
target_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5798450 entries, 0 to 5798449
Data columns (total 3 columns):
 #   Column  Dtype
---  ------  -----
 0   id      object
 1   name    object
 2   role    object
dtypes: object(3)
memory usage: 132.7+ MB

## Column "name"

In [3]:
df = gen_char_frequency_df(target_df["name"])
df_head = df.head(100)
df_tail = df.tail(1000)

In [4]:
fig = px.bar(x=df_head["character"], y =df_head["frequency"])
fig.show()

In [5]:
fig_tail = px.bar(x=df_tail["character"], y =df_tail["frequency"])
fig_tail.show()

In [6]:
# pattern = r"[^\p{L}\p{M}\s\-\']+" // required library "regex"
pattern = r"[^\w\x00-\x7F]"

special_char_df = df[df["character"].str.contains(pattern, regex=True)]
special_char_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93 entries, 65 to 2378
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   character  93 non-null     object
 1   frequency  93 non-null     int64
dtypes: int64(1), object(1)
memory usage: 2.2+ KB

In [7]:
fig_symbol = px.bar(x=special_char_df["character"], y=special_char_df["frequency"])
fig_symbol.show()

In [8]:
pd.set_option('display.max_rows', None)
special_char_df

     character  frequency
65           ̇       3349
107          ’        876
151          ”        225
152          «        225
153          »        225
156          “        211
158          ́        204
190          ิ        147
206          ั        115
214          ์        102
228                    87
232          ‘         85
233          ﻿         84
257          ุ         66
262          ̄         59
293          ​         44
309          ·         39
311          ่         39
330          „         35
334          ̈         34
337          ี         33
343          ้         32
349          ­         31
414          ̣         21
441          ´         20
460          ู         19
463          ‎         19
480          –         17
506          ‏         16
532          ̃         15
549          ・         14
624          ื         11
659          ̧         11
688          ）         10
750          ̀          9
813          া          7
851          ̌          7
910
          6
935          （          6
936          ๊          6
955          ្          6
957          ‑          6
974          ِ          6
983          ］          6
984          ［          6
989          —          6
1003         ′          5
1076         •          5
1083         ็          5
1097         ি          5
1131         ⽥          4
1132         ា          4
1139         ̂          4
1145                    4
1212         ⁠          4
1276         ̆          3
1312         ̊          3
1364         　          3
1380         ̉          3
1395         េ          3
1513                    2
1518         ️          2
1541         ¨          2
1631         🤣          2
1638         ី          2
1649         ‐          2
1659         ោ          2
1661         ូ          2
1812         ⽊          2
1813         ⼝          2
1842         ⼭          1
1843         ⼩          1
1844         ⽚          1
1974         ̲          1
2034         ∞          1
2037         °          1
2075         ¶          1
2106         ๋          1
2115         ̨          1
2117         ★          1
2141         ︠          1
2142         ︡          1
2157         ‌          1
2158                    1
2202                    1
2222         ّ          1
2305         ៍          1
2306         ុ          1
2312         ិ          1
2347         ึ          1
2359         🦇          1
2376         ী          1
2378         ু          1

In [9]:
pd.reset_option('display.max_rows')

In [10]:
target_df_no_na_df = target_df.dropna()
target_df_no_na_df[target_df_no_na_df["name"].str.contains(r"«")]

              id                           name                role
274458   1007214         José «Saza» Sazatornil       Administrator
428390   1013333         José «Saza» Sazatornil  Corporal Gutiérrez
440248   1013848       Pedro «Pedrucho» Basauri        Il "Maestro"
462070   1014832        Alberto «Atabar» Pedret         Voz locutor
526811   1017848  Gabriel «Chino» Marín Catalán           El Escape
...          ...                            ...                 ...
5629554  1850284          Alain « Al1 » Clément             guitars
5629558  1850284          Steeve « Zuul » Petit         Lead vocals
5680436  1873902            Josep «Kitflus» Mas            Teclados
5691525  1879131  Enrique Villareal «El Drogas»          Voz y bajo
5691526  1879131        Javier «Boni» Hernández      Voz y guitarra

[179 rows x 3 columns]

In [11]:
target_df_no_na_df[target_df_no_na_df["name"].str.contains(r"℃")]

Empty DataFrame
Columns: [id, name, role]
Index: []

## Column "role"

In [12]:
df = gen_char_frequency_df(target_df["role"])
df_head = df.head(100)
df_tail = df.tail(1000)

In [13]:
fig = px.bar(x=df_head["character"], y =df_head["frequency"])
fig.show()

In [14]:
fig_tail = px.bar(x=df_tail["character"], y =df_tail["frequency"])
fig_tail.show()

In [17]:
# pattern = r"[^\p{L}\p{M}\s\-\']+" // required library "regex"
pattern = r"[^\w\x00-\x7F]"

special_char_df = df[df["character"].str.contains(pattern, regex=True)].reset_index(drop=True)
special_char_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   character  159 non-null    object
 1   frequency  159 non-null    int64
dtypes: int64(1), object(1)
memory usage: 2.6+ KB

In [18]:
special_char_df

    character  frequency
0           ’       2337
1           «       1006
2           »        998
3           –        873
4           ̇        789
..        ...        ...
154         ី          1
155         ិ          1
156         ូ          1
157         ★          1
158         ်          1

[159 rows x 2 columns]

In [19]:
fig = px.bar(x=special_char_df["character"], y =special_char_df["frequency"])
fig.show()