# Bronze - Crew - Column Characters Frequency Explore

In [1]:
import pandas as pd
import plotly.express as px
from letterboxd_data_pipeline.load_data import load_files_from_layer
from letterboxd_data_pipeline.explore_data.char_frequency import gen_char_frequency_df

bronze_df = load_files_from_layer(layer="bronze", file_list=["crew.parquet"])
target_df = bronze_df["crew"]

Start loading data...
Loading: data/bronze/crew.parquet
Done!
Finish loading.

In [ ]:
target_df.info()

## Column "name"

In [2]:
df = gen_char_frequency_df(target_df["name"])
df_head = df.head(100)
df_tail = df.tail(1000)

In [3]:
fig = px.bar(x=df_head["character"], y =df_head["frequency"])
fig.show()

In [4]:
fig_tail = px.bar(x=df_tail["character"], y =df_tail["frequency"])
fig_tail.show()

In [5]:
# pattern = r"[^\p{L}\p{M}\s\-\']+" // required library "regex"
pattern = r"[^\w\x00-\x7F]"

special_char_df = df[df["character"].str.contains(pattern, regex=True)]
special_char_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 72 entries, 71 to 1989
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   character  72 non-null     object
 1   frequency  72 non-null     int64
dtypes: int64(1), object(1)
memory usage: 1.7+ KB

In [6]:
fig_symbol = px.bar(x=special_char_df["character"], y=special_char_df["frequency"])
fig_symbol.show()

In [7]:
pd.set_option('display.max_rows', None)
special_char_df

     character  frequency
71           ̇       1636
98           ’        756
120          ́        347
164          ”        113
167          “        111
172          ​        100
194                    77
196          ­         72
201          ﻿         66
218          ‎         56
220          «         52
221          »         52
224          ̄         49
232          ̈         43
247          ‘         39
252          –         37
276          ·         28
278          ‍         26
296          ´         24
312          ̃         20
325          ・         19
327          ั         19
332          ِ         18
334          （         18
336          ิ         18
353          ̀         16
360          ้         16
431          ่         11
432          　         11
443          ี         11
458          ‌         10
478          ์          9
490          ̊          9
510          ̌          9
553                     8
568
          7
592          ̆          7
630          ™          6
633          ̂          6
646          ุ          6
698          ๊          5
704          ื          5
774          ☆          5
780          ̣          4
806                     4
818          ّ          4
842          ู          4
888          „          4
940          ̧          3
962          †          3
1028         ∞          3
1106         •          2
1125         ̩          2
1132         ‪          2
1227         ̨          2
1244         ¨          2
1267         ）          2
1291         ‐          2
1303         —          2
1370         ¡          1
1371         ☺          1
1485         ℃          1
1521         ♂          1
1554         ⁣          1
1695         ⁠          1
1756         ՛          1
1767         ⽜          1
1863         ©          1
1878         🦇          1
1883         °          1
1948                    1
1989         ⼩          1

In [8]:
pd.reset_option('display.max_rows')

In [9]:
target_df_no_na_df = target_df.dropna()
target_df_no_na_df[target_df_no_na_df["name"].str.contains(r"«")]

              id                role                             name
297445   1006475               Sound       Antonio «Mármol» Rodríguez
333177   1007706               Sound             Miguel «Maiki» Calvo
347345   1008262               Sound             Miguel «Maiki» Calvo
373201   1009204      Visual effects                Iñaki «Ketxu» Gil
493269   1014463               Sound             Miguel «Maiki» Calvo
597525   1019977      Visual effects                Iñaki «Ketxu» Gil
691288   1025670               Sound       Antonio «Mármol» Rodríguez
696147   1025960               Sound       Antonio «Mármol» Rodríguez
701178   1026276               Sound       Antonio «Mármol» Rodríguez
775479   1031218               Sound       Antonio «Mármol» Rodríguez
787274   1032037               Sound             Miguel «Maiki» Calvo
802066   1033073               Sound             Miguel «Maiki» Calvo
920316   1041970               Sound             Miguel «Maiki» Calvo
922623   1042143               Sound       Antonio «Mármol» Rodríguez
989741   1047727               Sound       Antonio «Mármol» Rodríguez
1069685  1054762      Visual effects                Iñaki «Ketxu» Gil
1079695  1055666               Songs          Roque «Jarrito» Montoya
1096123  1057207               Sound             Miguel «Maiki» Calvo
1113796  1058894            Lighting            Rafael «Gato» Mac Kay
1113802  1058894            Composer            Jorge «Chino» Sabogal
1157239  1063020               Sound       Antonio «Mármol» Rodríguez
1660208  1120452            Composer       Ramsés «El Coleta» Gallego
1867894  1149495               Sound       Antonio «Mármol» Rodríguez
1989492  1167766              Writer          Alberto «Atabar» Pedret
2006865  1170522               Sound             Miguel «Maiki» Calvo
2013543  1171592               Sound       Antonio «Mármol» Rodríguez
2119533  1188608            Composer              Josep «Kitflus» Mas
2168870  1196829               Sound             Miguel «Maiki» Calvo
2196722  1201562               Sound             Miguel «Maiki» Calvo
2243291  1209672  Assistant director          Daniel «El Lobo» Blasco
2349961  1229078               Sound       Antonio «Mármol» Rodríguez
2497833  1257328               Songs  Miguel «Bambino» Vargas Jiménez
2643772  1287316            Composer              Josep «Kitflus» Mas
2787865  1318797            Composer              Josep «Kitflus» Mas
2879423  1339268            Composer              Josep «Kitflus» Mas
2979955  1362638               Sound       Antonio «Mármol» Rodríguez
3023668  1373108               Sound       Antonio «Mármol» Rodríguez
3153520  1404547              Writer           Joaquín «Top» Portillo
3206129  1417842            Composer              Josep «Kitflus» Mas
3228573  1423360            Composer              Josep «Kitflus» Mas
3248585  1428353  Executive producer          Alberto «Atabar» Pedret
3387621  1464296            Producer       Yolanda «Yolandoska» Pérez
3605112  1524585            Composer            Jorge «Chino» Sabogal
3660730  1540756            Composer            Jorge «Chino» Sabogal
3802305  1584316            Composer              Josep «Kitflus» Mas
3899486  1614751               Sound          Luc « NxProd » Loncelle
3908632  1617661               Sound          Luc « NxProd » Loncelle
4065443  1669372               Sound             Miguel «Maiki» Calvo
4097386  1680173            Director       Ramsés «El Coleta» Gallego
4097387  1680173              Writer       Ramsés «El Coleta» Gallego
4097392  1680173       Art direction       Ramsés «El Coleta» Gallego
4459164  1814616               Sound             Miguel «Maiki» Calvo

In [10]:
target_df_no_na_df[target_df_no_na_df["name"].str.contains(r"℃")]

              id      role   name
3499661  1494787  Director  Mon ℃

## Column "role"

In [11]:
df = gen_char_frequency_df(target_df["role"])
df_head = df.head(100)
df_tail = df.tail(1000)

In [12]:
fig = px.bar(x=df_head["character"], y =df_head["frequency"])
fig.show()

In [13]:
fig_tail = px.bar(x=df_tail["character"], y =df_tail["frequency"])
fig_tail.show()

In [14]:
# pattern = r"[^\p{L}\p{M}\s\-\']+" // required library "regex"
pattern = r"[^\w\x00-\x7F]"

special_char_df = df[df["character"].str.contains(pattern, regex=True)]
special_char_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   character  0 non-null      object
 1   frequency  0 non-null      int64
dtypes: int64(1), object(1)
memory usage: 0.0+ bytes

In [17]:
special_char_df

Empty DataFrame
Columns: [character, frequency]
Index: []