# Bronze - Movies Data

## Setup Environment and Prepare data

In [1]:
import config
from letterboxd_data_pipeline.load_data import load_files_from_layer
import numpy as np

# bronze_df = load_files_from_layer(layer="bronze", file_list=["movies"])
bronze_movies_df =load_files_from_layer(layer="bronze", file_list=["movies"])["movies"]

Start loading data...
Loading: ../data/bronze/movies
Done!
Finish loading.

## Simple Explore

In [2]:
bronze_movies_df.describe(include="all")

,id,name,date,tagline,description,minute,rating
count,9.415970e+05,941587,849684.000000,139387,780785,760027.000000,90999.000000
unique,NaN,795421,NaN,135521,763348,NaN,NaN
top,NaN,Home,NaN,animation short,Mexican feature film,NaN,NaN
freq,NaN,143,NaN,100,893,NaN,NaN
mean,1.470799e+06,NaN,1998.522300,NaN,NaN,65.776516,3.244043
std,2.718158e+05,NaN,27.534865,NaN,NaN,154.828161,0.417281
min,1.000001e+06,NaN,1874.000000,NaN,NaN,1.000000,0.880000
25%,1.235400e+06,NaN,1986.000000,NaN,NaN,15.000000,3.020000
50%,1.470799e+06,NaN,2010.000000,NaN,NaN,62.000000,3.300000
75%,1.706198e+06,NaN,2019.000000,NaN,NaN,92.000000,3.510000
max,1.941597e+06,NaN,2031.000000,NaN,NaN,72000.000000,4.690000

In [3]:
bronze_movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 941597 entries, 0 to 941596
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   id           941597 non-null  int64
 1   name         941587 non-null  object
 2   date         849684 non-null  float64
 3   tagline      139387 non-null  object
 4   description  780785 non-null  object
 5   minute       760027 non-null  float64
 6   rating       90999 non-null   float64
dtypes: float64(3), int64(1), object(3)
memory usage: 50.3+ MB

In [4]:
bronze_movies_df.head(10)

,id,name,date,tagline,description,minute,rating
0,1000001,Barbie,2023.0,She's everything. He's just Ken.,Barbie and Ken are having the time of their li...,114.0,3.86
1,1000002,Parasite,2019.0,Act like you own the place.,"All unemployed, Ki-taek's family takes peculia...",133.0,4.56
2,1000003,Everything Everywhere All at Once,2022.0,The universe is so much bigger than you realize.,An aging Chinese immigrant is swept up in an i...,140.0,4.30
3,1000004,Fight Club,1999.0,Mischief. Mayhem. Soap.,A ticking-time-bomb insomniac and a slippery s...,139.0,4.27
4,1000005,La La Land,2016.0,Here's to the fools who dream.,"Mia, an aspiring actress, serves lattes to mov...",129.0,4.09
5,1000006,Oppenheimer,2023.0,The world forever changes.,The story of J. Robert Oppenheimer's role in t...,181.0,4.23
6,1000007,Interstellar,2014.0,Mankind was born on Earth. It was never meant ...,The adventures of a group of explorers who mak...,169.0,4.35
7,1000008,Joker,2019.0,Put on a happy face.,"During the 1980s, a failed stand-up comedian i...",122.0,3.85
8,1000009,Dune,2021.0,"Beyond fear, destiny awaits.","Paul Atreides, a brilliant and gifted young ma...",155.0,3.90
9,1000010,Pulp Fiction,1994.0,Just because you are a character doesn't mean ...,"A burger-loving hit man, his philosophical par...",154.0,4.26

## Number of NA

In [5]:
bronze_movies_df.isna().sum()

id                  0
name               10
date            91913
tagline        802210
description    160812
minute         181570
rating         850598
dtype: int64

## Most Popular Movie Name

In [8]:
# Always use this line to sample the entire data to verify the code swiftly
popular_name_df = bronze_movies_df.copy(True)

popular_name_df.groupby("name").agg(total_count=("id","count")).sort_values(by="total_count", ascending=False)

                               total_count
name
Home                                   143
Untitled                               118
Alone                                  108
Mother                                  98
Love                                    76
...                                    ...
History of Manawan - Part Two            1
History of Manawan – Part Two            1
History of Memory                        1
History of Micronesia                    1
History of Hell                          1

[795421 rows x 1 columns]