# Bronze - Themes Data

## Setup Environment and Prepare data

In [1]:
import config
from letterboxd_data_pipeline.load_data import load_files_from_layer

bronze_df = load_files_from_layer(layer="bronze", file_list=["themes"])
bronze_themes_df = bronze_df["themes"]

Start loading data...
Loading: ../data/bronze/themes
Done!
Finish loading.

## Simple Explore

In [2]:
bronze_themes_df.describe(include="all")

                  id                        theme
count   1.256410e+05                       125641
unique           NaN                          109
top              NaN  Moving relationship stories
freq             NaN                         4012
mean    1.023455e+06                          NaN
std     3.865890e+04                          NaN
min     1.000001e+06                          NaN
25%     1.005213e+06                          NaN
50%     1.013261e+06                          NaN
75%     1.028295e+06                          NaN
max     1.849827e+06                          NaN

In [3]:
bronze_themes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125641 entries, 0 to 125640
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   id      125641 non-null  int64
 1   theme   125641 non-null  object
dtypes: int64(1), object(1)
memory usage: 1.9+ MB

In [4]:
bronze_themes_df.head(10)

        id                                              theme
0  1000001                   Humanity and the world around us
1  1000001                             Crude humor and satire
2  1000001                        Moving relationship stories
3  1000001     Emotional and captivating fantasy storytelling
4  1000001  Surreal and thought-provoking visions of life ...
5  1000001                 Quirky and endearing relationships
6  1000001                     Amusing jokes and witty satire
7  1000001          Laugh-out-loud relationship entanglements
8  1000002                   Humanity and the world around us
9  1000002          Intense violence and sexual transgression

## Most popular theme

In [5]:
bronze_themes_df.groupby("theme").agg(count=("id","count")).sort_values(by="count", ascending=False)

                                            count
theme
Moving relationship stories                  4012
Crude humor and satire                       3816
Horror, the undead and monster classics      3742
Twisted dark psychological thriller          3315
Gory, gruesome, and slasher horror           3132
...                                           ...
Captivating vision and Shakespearean drama    277
Air pilot heroism and survival                216
Underdog fighting and boxing stories          183
Teen friendship and coming-of-age              92
Engaging, intense crime and casino drama       68

[109 rows x 1 columns]

## Number of NA

In [9]:
bronze_themes_df.isna().sum()
# calculate NA references: https://stackoverflow.com/a/26266451/7939633

id       0
theme    0
dtype: int64

## Movie with most themes

In [ ]:
bronze_themes_df.groupby("id").agg(total_themes=("theme", "count")).sort_values(by="total_themes",ascending=False)

         total_themes
id
1002707            10
1002252            10
1001919            10
1003610            10
1000419            10
...               ...
1047566             1
1044411             1
1044532             1
1016208             1
1005814             1

[24508 rows x 1 columns]