# Bronze - Actors Data

## Setup Environment and Prepare data

In [12]:
import config
from letterboxd_data_pipeline.load_data import load_files_from_layer
import numpy as np

bronze_df = load_files_from_layer(layer="bronze", file_list=["actors"])
bronze_actors_df = bronze_df["actors"]

Start loading data...
Loading: ../data/bronze/actors
Done!
Finish loading.

## Simple Explore

In [2]:
bronze_actors_df.describe(include="all")

                  id       name     role
count   5.798450e+06    5798446  4436891
unique           NaN    1600662  1920085
top              NaN  Mel Blanc     Self
freq             NaN       1058   188502
mean    1.302557e+06        NaN      NaN
std     2.551917e+05        NaN      NaN
min     1.000001e+06        NaN      NaN
25%     1.079557e+06        NaN      NaN
50%     1.236225e+06        NaN      NaN
75%     1.483358e+06        NaN      NaN
max     1.941597e+06        NaN      NaN

In [3]:
bronze_actors_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5798450 entries, 0 to 5798449
Data columns (total 3 columns):
 #   Column  Dtype
---  ------  -----
 0   id      int64
 1   name    object
 2   role    object
dtypes: int64(1), object(2)
memory usage: 132.7+ MB

In [5]:
bronze_actors_df.head(10)

        id               name    role
0  1000001      Margot Robbie  Barbie
1  1000001       Ryan Gosling     Ken
2  1000001    America Ferrera  Gloria
3  1000001  Ariana Greenblatt   Sasha
4  1000001           Issa Rae  Barbie
5  1000001      Kate McKinnon  Barbie
6  1000001    Alexandra Shipp  Barbie
7  1000001        Emma Mackey  Barbie
8  1000001           Hari Nef  Barbie
9  1000001      Sharon Rooney  Barbie

## Number of NA

In [4]:
bronze_actors_df.isna().sum()

id            0
name          4
role    1361559
dtype: int64

## Most high risk schizophrenic actor (One actor in multiple character per movie)

In [17]:
talented_actor_df = bronze_actors_df.copy(True)

grouped_source_df = talented_actor_df.groupby(by=["id", "name"])

talented_actor_df["role_count"] = grouped_source_df["name"].transform(np.size)

talented_actor_df = talented_actor_df[
    ["id", "name", "role", "role_count"]
].sort_values(["id", "role_count", "name"], ascending=[True, False, True])

talented_actor_df

              id                 name          role  role_count
147      1000001       Aaron J. Smith        Dancer         1.0
88       1000001           Adam Blaug        Dancer         1.0
100      1000001        Adam Crossley        Dancer         1.0
110      1000001         Adam Fogarty        Dancer         1.0
144      1000001  Adam Paul Robertson        Dancer         1.0
...          ...                  ...           ...         ...
5798442  1941596          Nick Cheung  Zhang Yao/张耀         1.0
5798444  1941596       Sandrine Pinna          None         1.0
5798446  1941596                  线雨轩       Tata/塔塔         1.0
5798448  1941597       Hiroshi Mikami          None         1.0
5798449  1941597        Keiko Oginome          None         1.0

[5798450 rows x 4 columns]