# Bronze - Studios Data

## Setup Environment and Prepare data

In [1]:
import config
from letterboxd_data_pipeline.load_data import load_files_from_layer

# bronze_df = load_files_from_layer(layer="bronze", file_list=["studios"])
bronze_studios_df = load_files_from_layer(layer="bronze", file_list=["studios"])["studios"]

Start loading data...
Loading: ../data/bronze/studios
Done!
Finish loading.

## Simple Explore

In [2]:
bronze_studios_df.describe(include="all")

                  id  studio
count   6.792830e+05  679273
unique           NaN  160881
top              NaN     BBC
freq             NaN    3560
mean    1.319075e+06     NaN
std     2.660925e+05     NaN
min     1.000001e+06     NaN
25%     1.083656e+06     NaN
50%     1.249924e+06     NaN
75%     1.516158e+06     NaN
max     1.941596e+06     NaN

In [3]:
bronze_studios_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 679283 entries, 0 to 679282
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   id      679283 non-null  int64
 1   studio  679273 non-null  object
dtypes: int64(1), object(1)
memory usage: 10.4+ MB

In [4]:
bronze_studios_df.head(10)

        id                   studio
0  1000001  LuckyChap Entertainment
1  1000001             Heyday Films
2  1000001           NB/GG Pictures
3  1000001                   Mattel
4  1000001    Warner Bros. Pictures
5  1000002             Barunson E&A
6  1000003                IAC Films
7  1000003                     AGBO
8  1000003   Ley Line Entertainment
9  1000003          Year of the Rat

## Number of NA

In [5]:
bronze_studios_df.isna().sum()

id         0
studio    10
dtype: int64

## Movie with Most Studios

In [20]:
most_studios_df = bronze_studios_df.copy(True)

most_studios_df = most_studios_df.drop_duplicates()

most_studios_df["studio_count"] = (
    most_studios_df.groupby(by=["id"])["studio"]
    .transform(lambda x: x.nunique())
)

most_studios_df.sort_values(["studio_count", "id"], ascending=[False, True])

             id                      studio  studio_count
156215  1074178          Bona Entertainment            29
156216  1074178  Sil-Metropole Organisation            29
156217  1074178                  Pop Movies            29
156218  1074178          Cathay-Keris Films            29
156219  1074178               Twin Co. Ltd.            29
...         ...                         ...           ...
546247  1590891                        None             0
553224  1605792                        None             0
572686  1648488                        None             0
597121  1706513                        None             0
677077  1934958                        None             0

[679071 rows x 3 columns]

## Duplicated Data

In [13]:
duplicated_df = bronze_studios_df.copy(True)
duplicated_df[duplicated_df.duplicated()]

             id                                            studio
146     1000044                               Working Title Films
487     1000165                               Working Title Films
810     1000263                               Working Title Films
1650    1000514                                            Fabula
1757    1000547                               Working Title Films
...         ...                                               ...
653433  1852028                                              ARTE
655761  1859604                                              ARTE
656807  1863229                                        Star Media
665454  1888903  Deutsche Film- und Fernsehakademie Berlin (DFFB)
677100  1934998                           Ministerstvo kultury ČR

[212 rows x 2 columns]

## Movie without Studios

In [39]:
without_studios_df = bronze_studios_df.copy(True)

without_studios_df.loc[without_studios_df["studio"].isna()]

             id studio
347347  1259717   None
411467  1350206   None
473794  1450762   None
534117  1565428   None
541076  1579904   None
546247  1590891   None
553224  1605792   None
572686  1648488   None
597121  1706513   None
677077  1934958   None